/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ChannelApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ChannelTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChatSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "EventLogTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MomentoApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
