-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Mutation exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AddConversationStepRequiredArguments =
    { input : Api.EssifyAI.InputObject.AddConversationStepInput }


{-| Adds a Step to an existing Conversation.
-}
addConversationStep :
    AddConversationStepRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.AddConversationStepPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
addConversationStep requiredArgs____ object____ =
    Object.selectionForCompositeField "addConversationStep" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeAddConversationStepInput ] object____ (Basics.identity >> Decode.nullable)


type alias AuthenticateRequiredArguments =
    { input : Api.EssifyAI.InputObject.AuthenticateInput }


{-| Authenticates a user and lets them retrieve their bearer token.
-}
authenticate :
    AuthenticateRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.AuthenticatePayload
    -> SelectionSet (Maybe decodesTo) RootMutation
authenticate requiredArgs____ object____ =
    Object.selectionForCompositeField "authenticate" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeAuthenticateInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateApiTokenRequiredArguments =
    { input : Api.EssifyAI.InputObject.CreateApiTokenInput }


{-| Allows users to create API tokens.
-}
createApiToken :
    CreateApiTokenRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.CreateApiTokenPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createApiToken requiredArgs____ object____ =
    Object.selectionForCompositeField "createApiToken" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeCreateApiTokenInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateConversationRequiredArguments =
    { input : Api.EssifyAI.InputObject.CreateConversationInput }


{-| Creates a new Conversation item.
-}
createConversation :
    CreateConversationRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.CreateConversationPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createConversation requiredArgs____ object____ =
    Object.selectionForCompositeField "createConversation" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeCreateConversationInput ] object____ (Basics.identity >> Decode.nullable)


type alias CreateDataroomPromptTemplateRequiredArguments =
    { input : Api.EssifyAI.InputObject.CreateDataroomPromptTemplateInput }


{-| Creates a new Prompt Template.
-}
createDataroomPromptTemplate :
    CreateDataroomPromptTemplateRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.CreateDataroomPromptTemplatePayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createDataroomPromptTemplate requiredArgs____ object____ =
    Object.selectionForCompositeField "createDataroomPromptTemplate" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeCreateDataroomPromptTemplateInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateAgentsRequiredArguments =
    { input : Api.EssifyAI.InputObject.UpdateAgentsInput }


{-| Orders the system to update hosted agents.
-}
updateAgents :
    UpdateAgentsRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.UpdateAgentsPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateAgents requiredArgs____ object____ =
    Object.selectionForCompositeField "updateAgents" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeUpdateAgentsInput ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateUserRequiredArguments =
    { input : Api.EssifyAI.InputObject.UpdateUserInput }


{-| Updates a given User.
-}
updateUser :
    UpdateUserRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.UpdateUserPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateUser requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs____.input Api.EssifyAI.InputObject.encodeUpdateUserInput ] object____ (Basics.identity >> Decode.nullable)
