-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object exposing (..)


type AddConversationStepPayload
    = AddConversationStepPayload


type ApiToken
    = ApiToken


type ApiTokenConnection
    = ApiTokenConnection


type ApiTokenEdge
    = ApiTokenEdge


type ArbitraryPipelineTracePayload
    = ArbitraryPipelineTracePayload


type AuthenticatePayload
    = AuthenticatePayload


type Conversation
    = Conversation


type ConversationConnection
    = ConversationConnection


type ConversationEdge
    = ConversationEdge


type ConversationHistoryItem
    = ConversationHistoryItem


type ConversationStep
    = ConversationStep


type ConversationStepConnection
    = ConversationStepConnection


type ConversationStepEdge
    = ConversationStepEdge


type CreateApiTokenPayload
    = CreateApiTokenPayload


type CreateConversationPayload
    = CreateConversationPayload


type CreateDataroomPromptTemplatePayload
    = CreateDataroomPromptTemplatePayload


type Dataroom
    = Dataroom


type DataroomConnection
    = DataroomConnection


type DataroomEdge
    = DataroomEdge


type DataroomPromptTemplate
    = DataroomPromptTemplate


type DataroomPromptTemplateConnection
    = DataroomPromptTemplateConnection


type DataroomPromptTemplateEdge
    = DataroomPromptTemplateEdge


type KnowledgeGraphPipelineTracePayload
    = KnowledgeGraphPipelineTracePayload


type LlmQueryPipelineTracePayload
    = LlmQueryPipelineTracePayload


type PageInfo
    = PageInfo


type PipelineTrace
    = PipelineTrace


type PipelineTraceConnection
    = PipelineTraceConnection


type PipelineTraceEdge
    = PipelineTraceEdge


type PromptTemplateBindingSpec
    = PromptTemplateBindingSpec


type Session
    = Session


type UpdateAgentsPayload
    = UpdateAgentsPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type VectorsPipelineTracePayload
    = VectorsPipelineTracePayload
