-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Query exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Checks a bearer token and returns the User and Session matching it - if valid.
-}
me :
    SelectionSet decodesTo Api.EssifyAI.Object.User
    -> SelectionSet decodesTo RootQuery
me object____ =
    Object.selectionForCompositeField "me" [] object____ Basics.identity


type alias NodeRequiredArguments =
    { id : Api.EssifyAI.CustomScalarCodecs.Id }


{-| This endpoint allows to directly query nodes of type User and Conversation.

  - id - The ID of an object.

-}
node :
    NodeRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Interface.Node
    -> SelectionSet (Maybe decodesTo) RootQuery
node requiredArgs____ object____ =
    Object.selectionForCompositeField "node" [ Argument.required "id" requiredArgs____.id (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


{-| A query allowing to obtain server-side settings and environment information.
-}
settings : SelectionSet Api.EssifyAI.CustomScalarCodecs.Json RootQuery
settings =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Json" "settings" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecJson |> .decoder)
