-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.ScalarCodecs exposing (..)

import Api.EssifyAI.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    Api.EssifyAI.Scalar.DateTime


type alias Id =
    Api.EssifyAI.Scalar.Id


type alias Json =
    Api.EssifyAI.Scalar.Json


codecs : Api.EssifyAI.Scalar.Codecs DateTime Id Json
codecs =
    Api.EssifyAI.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        , codecJson = defaultCodecs.codecJson
        }
