-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Subscription exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias ConversationStepCreatedRequiredArguments =
    { bearerToken : String
    , id : Api.EssifyAI.CustomScalarCodecs.Id
    }


{-| Triggers whenever a Conversation Step is added to a Conversation.

  - bearerToken - The Bearer Token used to authenticate the subscription.
  - id - The GID of the Conversation to subscribe to.

-}
conversationStepCreated :
    ConversationStepCreatedRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.ConversationStep
    -> SelectionSet decodesTo RootSubscription
conversationStepCreated requiredArgs____ object____ =
    Object.selectionForCompositeField "conversationStepCreated" [ Argument.required "bearerToken" requiredArgs____.bearerToken Encode.string, Argument.required "id" requiredArgs____.id (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapEncoder .codecId) ] object____ Basics.identity


type alias UserUpdatedRequiredArguments =
    { bearerToken : String
    , id : Api.EssifyAI.CustomScalarCodecs.Id
    }


{-| This subscription will trigger whenever a User is updated.

  - bearerToken - The Bearer Token used to authenticate the subscription.
  - id - The GID of the User to subscribe to.

-}
userUpdated :
    UserUpdatedRequiredArguments
    -> SelectionSet decodesTo Api.EssifyAI.Object.User
    -> SelectionSet decodesTo RootSubscription
userUpdated requiredArgs____ object____ =
    Object.selectionForCompositeField "userUpdated" [ Argument.required "bearerToken" requiredArgs____.bearerToken Encode.string, Argument.required "id" requiredArgs____.id (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapEncoder .codecId) ] object____ Basics.identity
