-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.VerifyScalarCodecs exposing (..)

{-
   This file is intended to be used to ensure that custom scalar decoder
   files are valid. It is compiled using `elm make` by the CLI.
-}

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.Scalar


verify : Api.EssifyAI.Scalar.Codecs Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.CustomScalarCodecs.Json
verify =
    Api.EssifyAI.CustomScalarCodecs.codecs
