-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.AuthenticatePayload exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


session :
    SelectionSet decodesTo Api.EssifyAI.Object.Session
    -> SelectionSet decodesTo Api.EssifyAI.Object.AuthenticatePayload
session object____ =
    Object.selectionForCompositeField "session" [] object____ Basics.identity


user :
    SelectionSet decodesTo Api.EssifyAI.Object.User
    -> SelectionSet decodesTo Api.EssifyAI.Object.AuthenticatePayload
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity
