-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.ConversationStep exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.Enum.ConversationStepRole
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The initial user input that was used for this Step.
-}
content : SelectionSet String Api.EssifyAI.Object.ConversationStep
content =
    Object.selectionForField "String" "content" [] Decode.string


{-| The parent Conversation to which this Step belongs to.
-}
conversation :
    SelectionSet decodesTo Api.EssifyAI.Object.Conversation
    -> SelectionSet decodesTo Api.EssifyAI.Object.ConversationStep
conversation object____ =
    Object.selectionForCompositeField "conversation" [] object____ Basics.identity


{-| Arbitrary data that was attached when creating this Step.
-}
data : SelectionSet Api.EssifyAI.CustomScalarCodecs.Json Api.EssifyAI.Object.ConversationStep
data =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Json" "data" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecJson |> .decoder)


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.ConversationStep
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The entity's creation timestamp.
-}
insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.ConversationStep
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The role of the participant from which this Step originated.
-}
role : SelectionSet Api.EssifyAI.Enum.ConversationStepRole.ConversationStepRole Api.EssifyAI.Object.ConversationStep
role =
    Object.selectionForField "Enum.ConversationStepRole.ConversationStepRole" "role" [] Api.EssifyAI.Enum.ConversationStepRole.decoder


type alias TracesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The traces that were generated during the processing of this Step.
-}
traces :
    (TracesOptionalArguments -> TracesOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.PipelineTraceConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.ConversationStep
traces fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "traces" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| The entity's last update timestamp.
-}
updatedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.ConversationStep
updatedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "updatedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
