-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.ConversationHistoryItem exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.Enum.ConversationStepRole
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


content : SelectionSet String Api.EssifyAI.Object.ConversationHistoryItem
content =
    Object.selectionForField "String" "content" [] Decode.string


insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.ConversationHistoryItem
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


role : SelectionSet Api.EssifyAI.Enum.ConversationStepRole.ConversationStepRole Api.EssifyAI.Object.ConversationHistoryItem
role =
    Object.selectionForField "Enum.ConversationStepRole.ConversationStepRole" "role" [] Api.EssifyAI.Enum.ConversationStepRole.decoder
