-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.Conversation exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Arbitrary data that was attached when creating this Conversation.
-}
data : SelectionSet Api.EssifyAI.CustomScalarCodecs.Json Api.EssifyAI.Object.Conversation
data =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Json" "data" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecJson |> .decoder)


type alias DataroomsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The Dataroom items that this Conversation uses to.
-}
datarooms :
    (DataroomsOptionalArguments -> DataroomsOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.DataroomConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.Conversation
datarooms fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "datarooms" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


history :
    SelectionSet decodesTo Api.EssifyAI.Object.ConversationHistoryItem
    -> SelectionSet (List decodesTo) Api.EssifyAI.Object.Conversation
history object____ =
    Object.selectionForCompositeField "history" [] object____ (Basics.identity >> Decode.list)


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.Conversation
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The entity's creation timestamp.
-}
insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.Conversation
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


type alias StepsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| Steps that have been taken in this Conversation.
-}
steps :
    (StepsOptionalArguments -> StepsOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.ConversationStepConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.Conversation
steps fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "steps" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| The title of this Conversation.
-}
title : SelectionSet String Api.EssifyAI.Object.Conversation
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The entity's last update timestamp.
-}
updatedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.Conversation
updatedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "updatedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
