-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.DataroomPromptTemplate exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Specification for bindings needed by the prompt content.
-}
bindings :
    SelectionSet decodesTo Api.EssifyAI.Object.PromptTemplateBindingSpec
    -> SelectionSet (List decodesTo) Api.EssifyAI.Object.DataroomPromptTemplate
bindings object____ =
    Object.selectionForCompositeField "bindings" [] object____ (Basics.identity >> Decode.list)


{-| The prompt content itself.
-}
content : SelectionSet String Api.EssifyAI.Object.DataroomPromptTemplate
content =
    Object.selectionForField "String" "content" [] Decode.string


{-| The User to whom the Dataroom belongs to.
-}
dataroom :
    SelectionSet decodesTo Api.EssifyAI.Object.Dataroom
    -> SelectionSet decodesTo Api.EssifyAI.Object.DataroomPromptTemplate
dataroom object____ =
    Object.selectionForCompositeField "dataroom" [] object____ Basics.identity


{-| Whether this Prompt Template is flagged as the default one for the parent Dataroom.
-}
default : SelectionSet Bool Api.EssifyAI.Object.DataroomPromptTemplate
default =
    Object.selectionForField "Bool" "default" [] Decode.bool


{-| The description for the Prompt Template.
-}
description : SelectionSet String Api.EssifyAI.Object.DataroomPromptTemplate
description =
    Object.selectionForField "String" "description" [] Decode.string


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.DataroomPromptTemplate
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The entity's creation timestamp.
-}
insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.DataroomPromptTemplate
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| A slug unique to the parent Dataroom that was derived from the Prompt Template title.
-}
slug : SelectionSet String Api.EssifyAI.Object.DataroomPromptTemplate
slug =
    Object.selectionForField "String" "slug" [] Decode.string


{-| The title for the Prompt Template.
-}
title : SelectionSet String Api.EssifyAI.Object.DataroomPromptTemplate
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The entity's last update timestamp.
-}
updatedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.DataroomPromptTemplate
updatedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "updatedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
