-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.Dataroom exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias ConversationsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The Conversations which use this Dataroom.
-}
conversations :
    (ConversationsOptionalArguments -> ConversationsOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.ConversationConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.Dataroom
conversations fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "conversations" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| The default Prompt Template associated with this Dataroom.
-}
defaultPromptTemplate :
    SelectionSet decodesTo Api.EssifyAI.Object.DataroomPromptTemplate
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.Dataroom
defaultPromptTemplate object____ =
    Object.selectionForCompositeField "defaultPromptTemplate" [] object____ (Basics.identity >> Decode.nullable)


description : SelectionSet String Api.EssifyAI.Object.Dataroom
description =
    Object.selectionForField "String" "description" [] Decode.string


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.Dataroom
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The entity's creation timestamp.
-}
insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.Dataroom
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


type alias PromptTemplatesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The Prompt Template entities configured in this Dataroom - excluding the default Prompt Template.
-}
promptTemplates :
    (PromptTemplatesOptionalArguments -> PromptTemplatesOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.DataroomPromptTemplateConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.Dataroom
promptTemplates fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "promptTemplates" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


title : SelectionSet String Api.EssifyAI.Object.Dataroom
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The entity's last update timestamp.
-}
updatedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.Dataroom
updatedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "updatedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The User to whom this Dataroom belongs to.
-}
user :
    SelectionSet decodesTo Api.EssifyAI.Object.User
    -> SelectionSet decodesTo Api.EssifyAI.Object.Dataroom
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity
