-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.PipelineTrace exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.PipelineTrace
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


logs : SelectionSet String Api.EssifyAI.Object.PipelineTrace
logs =
    Object.selectionForField "String" "logs" [] Decode.string


payload :
    SelectionSet decodesTo Api.EssifyAI.Union.PipelineTracePayload
    -> SelectionSet decodesTo Api.EssifyAI.Object.PipelineTrace
payload object____ =
    Object.selectionForCompositeField "payload" [] object____ Basics.identity


success : SelectionSet Bool Api.EssifyAI.Object.PipelineTrace
success =
    Object.selectionForField "Bool" "success" [] Decode.bool
