-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.PromptTemplateBindingSpec exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The name of the variable for the binding.
-}
name : SelectionSet String Api.EssifyAI.Object.PromptTemplateBindingSpec
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| Whether or not the variable is required at runtime.
-}
required : SelectionSet Bool Api.EssifyAI.Object.PromptTemplateBindingSpec
required =
    Object.selectionForField "Bool" "required" [] Decode.bool
