-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.EssifyAI.Object.User exposing (..)

import Api.EssifyAI.CustomScalarCodecs
import Api.EssifyAI.InputObject
import Api.EssifyAI.Interface
import Api.EssifyAI.Object
import Api.EssifyAI.Scalar
import Api.EssifyAI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias ApiTokensOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| All API Token entities created by this User.
-}
apiTokens :
    (ApiTokensOptionalArguments -> ApiTokensOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.ApiTokenConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.User
apiTokens fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "apiTokens" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias ConversationsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| All Conversation items created by this User or by one of their API sessions.
-}
conversations :
    (ConversationsOptionalArguments -> ConversationsOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.ConversationConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.User
conversations fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "conversations" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias DataroomsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| All Dataroom items created by this User.
-}
datarooms :
    (DataroomsOptionalArguments -> DataroomsOptionalArguments)
    -> SelectionSet decodesTo Api.EssifyAI.Object.DataroomConnection
    -> SelectionSet (Maybe decodesTo) Api.EssifyAI.Object.User
datarooms fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "datarooms" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| The default API Token associated with this user.
-}
defaultApiToken :
    SelectionSet decodesTo Api.EssifyAI.Object.ApiToken
    -> SelectionSet decodesTo Api.EssifyAI.Object.User
defaultApiToken object____ =
    Object.selectionForCompositeField "defaultApiToken" [] object____ Basics.identity


{-| This User's email address.
-}
email : SelectionSet String Api.EssifyAI.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


{-| This User's full name.
-}
fullName : SelectionSet String Api.EssifyAI.Object.User
fullName =
    Object.selectionForField "String" "fullName" [] Decode.string


{-| The ID of an object
-}
id : SelectionSet Api.EssifyAI.CustomScalarCodecs.Id Api.EssifyAI.Object.User
id =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.Id" "id" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The entity's creation timestamp.
-}
insertedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.User
insertedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "insertedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Whether or not this user is an administrator.
-}
isAdmin : SelectionSet Bool Api.EssifyAI.Object.User
isAdmin =
    Object.selectionForField "Bool" "isAdmin" [] Decode.bool


{-| The entity's last update timestamp.
-}
updatedAt : SelectionSet Api.EssifyAI.CustomScalarCodecs.DateTime Api.EssifyAI.Object.User
updatedAt =
    Object.selectionForField "Api.EssifyAI.CustomScalarCodecs.DateTime" "updatedAt" [] (Api.EssifyAI.CustomScalarCodecs.codecs |> Api.EssifyAI.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
